name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests pyside6 pyinstaller

    - name: Build exe
      run: |
        pyinstaller --onefile --noconsole app.py

    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: streamfinder-exe
        path: dist/app.exe
